devtools::load_all()
r_data_dir_chr <- normalizePath("C:/Users/mahamilton/Desktop/Readyforwhatsnext/Data/R_Format")
data_pckg_chr <- "springtides"
pa_r4_chr <- "aus_pa_r4"
data(list = pa_r4_chr,
     package = data_pckg_chr,
     envir = environment())
eval(parse(text = paste0("pa_r4<-",pa_r4_chr)))
input <- list(area_name_chr = "Area Name",
              dateRange = c(Sys.Date(),(Sys.Date() + lubridate::years(5)) %>% min(pa_r4@temporal_max)),
              disorder_chr = "Any Common Mental Disorder",
              gdist_dbl = NA_real_,#30,
              gdist_ttime_chr = NA_character_,#"Geometric distance",
              meso2_bound_yr = 2016,
              meso2_chr = "Victoria",
              meso2_type_chr = "State and Territory",
              micro_chr_vec = NA_character_,#""Darwin",
              n_its_int = 10,
              pa_type_chr ="Predefined boundary",
              report_format_chr = "PDF",
              stat_chr = "Prevalence - Annual",
              ttime_dbl = NA_real_,
              uncertainty_int = c(0.025,0.975),
              user_name_chr = "TEST")
if(is.null(input$meso2_type_chr)){
  meso2_type_chr <- NA_character_
}else{
  meso2_type_chr <- ready4fun::get_from_lup(pa_r4@lookup_tb@sp_abbreviations_lup,
                                          lookup_variable = "long_name",
                                          lookup_reference = input$meso2_type_chr,
                                          target_variable = "short_name",
                                          evaluate = F)
}
if(is.null(input$meso2_chr)){
  meso2_chr <- NA_character_
}else{
  meso2_chr <- input$meso2_chr
}
if(is.null(input$micro_chr_vec)){
  micro_chr_vec <- NA_character_
}else{
  micro_chr_vec <- input$micro_chr_vec
}
params_ls <- list(age_lower = 04,
                  age_upper = 84,
                  authorship_1_chr =  "Report generated by the Orygen Springtides App",
                  authorship_2_chr =  paste0("Input parameters selected by ",input$user_name_chr),
                  data_pckg_chr = data_pckg_chr,
                  disorder_chr = input$disorder_chr %>%
                    stringr::str_replace_all(" ","_"),
                  format_chr = input$report_format_chr,
                  gdist_dbl = ifelse(input$pa_type_chr=="Predefined boundary",
                                     NA_real_,
                                     ifelse(is.null(input$gdist_dbl), NA_real_,input$gdist_dbl)),
                  gdist_ttime_chr = ifelse(input$pa_type_chr=="Predefined boundary",
                                           NA_character_
                                           ,ifelse(is.null(input$gdist_ttime_chr), NA_character_,input$gdist_ttime_chr)),
                  meso2_bound_yr = ifelse(input$pa_type_chr=="Predefined boundary",
                                          as.integer(input$meso2_bound_yr),
                                          NA_real_),
                  meso2_chr = NULL,
                  meso2_name_chr = springtides::make_area_name_chr(pa_r4 = pa_r4,
                                                                   pa_type_chr = input$pa_type_chr,
                                                                   area_type_chr = meso2_type_chr,
                                                                   feature_chr = meso2_chr,
                                                                   area_name_chr = input$area_name_chr),
                  meso2_type_chr = meso2_type_chr,
                  micro_chr_vec = micro_chr_vec,
                  model_end_date = min(input$dateRange[2] %>% lubridate::as_datetime(tz="Australia/Melbourne"), pa_r4@temporal_max),
                  model_start_date = max(input$dateRange[1] %>% lubridate::as_datetime(tz="Australia/Melbourne"), pa_r4@temporal_min),
                  n_its_int = input$n_its_int,
                  pa_r4_chr = pa_r4_chr,
                  pa_type_chr = input$pa_type_chr,
                  pdf_output_lgl = switch(input$report_format_chr,
                                          PDF = T,
                                          HTML = F,
                                          Word = T),
                  r_data_dir_chr = r_data_dir_chr,
                  rendered_by_shiny_lgl = F,
                  stat_chr = input$stat_chr,
                  ttime_dbl = ifelse(input$pa_type_chr=="Predefined boundary",
                                     NA_real_,
                                     ifelse(is.null(input$ttime_dbl), NA_real_,input$ttime_dbl)),
                  uncertainty_1_int = input$uncertainty_int[1],
                  uncertainty_2_int = input$uncertainty_int[2],
                  user_name_chr = input$user_name_chr)
if(is.null(input$meso2_chr)){
  meso2_chr <- NA_character_
}else{
  meso2_chr <- input$meso2_chr
}
params_ls$title_chr <- paste0("Predicted ",
                              springtides::tf_stat_chr(stat_chr = params_ls$stat_chr %>% tolower(),
                                                       disorder_chr = params_ls$disorder_chr),
                              " in young people aged ",
                              params_ls$age_lower,
                              " to ",
                              params_ls$age_upper,
                              " for ",
                              params_ls$meso2_name_chr,
                              " between ",
                              params_ls$model_start_date %>% format("%d %B %Y"),
                              " and ",
                              params_ls$model_end_date %>% format("%d %B %Y"))
params_ls$input_ls_path_chr <- params_ls$sim_data_r4_path_chr <- params_ls$sim_results_ls_path_chr <- NA_character_
output_params_ls <- springtides::make_output_params_ls(input_params_ls = params_ls)
