---
params:
  age_lower: 19
  age_upper: 22
  disorder_chr: Bipolar_Disorder_With_Psychosis
  gdist_dbl: !r NA_real_
  gdist_ttime_chr: !r NA_character_
  meso2_bound_yr: 2018
  meso2_chr: Aston
  meso2_name_chr: Aston Commonwealth Electoral Division
  meso2_type_chr: CED
  micro_chr_vec: !r NA_character_
  model_end_date: !r springtides::aus_pa_r4@temporal_max
  model_start_date: !r springtides::aus_pa_r4@temporal_min
  n_its_int: 10
  pa_type_chr: Predefined boundary
  pdf_output_lgl: !r T
  r_data_dir_chr: !r normalizePath("C:/Users/mahamilton/Desktop/Readyforwhatsnext/Data/R_Format")
  rendered_by_shiny_lgl: !r F
  stat_chr: Prevalence - Monthly
  title_chr: Springtides report
  ttime_dbl: !r NA_real_
  uncertainty_1_int: 0.025
  uncertainty_2_int: 0.975
  user_name_chr: Anonymous user
title: "`r params$title_chr`"
author: 
 - "Report generated by the Orygen Springtides App" 
 - "Input parameters selected by `r params$user_name_chr`"
date: "`r format.Date(Sys.Date(),'%B %d, %Y')`"
output:
  pdf_document:
    fig_caption: yes
  html_document:
    df_print: paged
header-includes: 
  - \usepackage{booktabs} 
  - \usepackage{longtable} 
  - \usepackage{array} 
  - \usepackage{multirow} 
  - \usepackage{wrapfig} 
  - \usepackage{float}
  - \usepackage{colortbl} 
  - \usepackage{pdflscape} 
  - \usepackage{tabu} 
  - \usepackage{threeparttable} 
  - \usepackage{threeparttablex}
  - \usepackage[normalem]{ulem} 
  - \usepackage{makecell} 
  - \usepackage{xcolor}
---

```{r echo=F, warning=F, include=F}
library(magrittr)
library(kableExtra)
# library(pander)
library(springtides)
# pander::panderOptions("table.split.table", Inf)
options(scipen=999)

```

```{r}
params
purrr::map(params,~class(.x))
```


```{r echo=F, warning=F, include=F}
if(params$rendered_by_shiny_lgl)
  shiny::setProgress(0.1, message = "Step one: Processing user inputs")
if(is.na(params$meso2_type_chr)){
  meso2_type_chr <- NULL
}else{
  meso2_type_chr <- params$meso2_type_chr
}
if(is.na(params$meso2_bound_yr)){
  meso2_bound_yr <- NULL
}else{
  meso2_bound_yr <- params$meso2_bound_yr
}

```


```{r echo=F, warning=F, include=F}
input_ls <- springtides::make_one_input_ls(pa_r4 = springtides::aus_pa_r4,
                               path_to_data_chr = params$r_data_dir_chr,
                               args_ls = list(age_range_int_vec = c(params$age_lower,params$age_upper),
                                            disorder_chr = params$disorder_chr %>%
                                              stringr::str_replace_all(" ","_"),
                                            gdist_ttime_chr = params$gdist_ttime_chr,
                                            gdist_dbl = params$gdist_dbl,
                                            meso1_chr = NA_character_,
                                            meso2_bound_yr = meso2_bound_yr,
                                            meso2_type_chr = meso2_type_chr,
                                            meso2_chr = params$meso2_chr,
                                            micro_chr_vec = params$micro_chr_vec,
                                            model_end_ymdhms = params$model_end_date,
                                            model_start_ymdhms = params$model_start_date,
                                            n_its_int = params$n_its_int,
                                            pa_type_chr = params$pa_type_chr,
                                            prob_lgl = params$n_its_int>1,
                                            stat_chr = params$stat_chr,
                                            ttime_dbl = params$ttime_dbl,
                                            # n_custom_services_int = n_custom_services_int,
                                            # custom_lat_dbl = get_lat_or_lon_dbl_vec(custom_coords_ls = custom_coords_ls),
                                            # custom_lon_dbl = get_lat_or_lon_dbl_vec(custom_coords_ls = custom_coords_ls,
                                            #                                         get_lat = F),
                                            uncertainty_int = c(params$uncertainty_1_int, 
                                                                params$uncertainty_2_int)))
```

```{r}
input_ls
purrr::map(input_ls,~class(.x))
input_ls$pa_r4 %>% ready4space::features()
```

